name: CI Docker
# Check builds on supported Linux distributions

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.rst'
      - '**.txt'

jobs:

  build:
    name: CI on ${{ matrix.tag }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: # Those are our ghcr.io/alire-project/docker/gnat:tag machines
            - centos-stream-fsf-latest # Test unsupported package manager
            - debian-stable            # Test current stable Debian compiler
            - fedora-latest            # Test current Fedora compiler
            - ubuntu-lts               # Test current LTS Ubuntu compiler
            - arch-rolling             # Test Arch compiler (closest to FSF?)

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: OS information for ${{ matrix.tag }}
      uses: mosteo-actions/docker-run@v2
      with:
        image: ghcr.io/alire-project/docker/gnat:${{matrix.tag}}
        command: |
          lsb_release -a || \
          cat /etc/os-release || \
          cat /etc/system-release || \
          echo "No lsb_release information"

    - name: Run test script (${{ matrix.tag }})
      uses: mosteo-actions/docker-run@v2
      with:
        image: ghcr.io/alire-project/docker/gnat:${{matrix.tag}}
        command: scripts/ci-github.sh
        params: -v${PWD}:/alire -w /alire

    - name: Upload logs (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: e3-log-docker-${{ matrix.tag }}.zip
        path: testsuite/out
